'''ancients.py : a dictionary of Minecraft Dungeons Ancient mobs'''

# _names : A list of Ancient names and their nicknames in my code
_names = {'?????': '?',
          'abominable_weaver': 'aw',
          'abyssal_eye': 'ae',
          'ancient_terror': 'at',
          'barrage': 'b',
          'cursed_presence': 'cp',
          'first_enchanter': 'fe',
          'frostwarden': 'f',
          'grim_guardian': 'gg',
          'haunted_caller': 'hc',
          'oozing_menace': 'om',
          'pestilent_conjurer': 'pc',
          'scuttling_torment': 'st',
          'solemn_giant': 'sg',
          'the_seeking_flame': 'tsf',
          'the_swarm': 'ts',
          'the_tiny_scourge': 'tts',
          'the_tower': 'tt',
          'the_unending': 'tu',
          'thundering_growth': 'tg',
          'unbreakable_one': 'uo',
          'unstoppable_tusk': 'ut',
          'vengeful_mariner': 'vm',
          'vigilant_scoundrel': 'vs',
          'watcher_of_the_end': 'wote',
          'windbeard': 'w'}

# _names_places : A list of Ancient nicknames and where they spawn
_names_places = {'?': '???',
                 'aw': 'Spider Cave',
                 'ae': 'Abyssal Monument',
                 'at': 'Underhalls',
                 'b': 'Highblock Halls',
                 'cp': 'Lower Temple',
                 'fe': 'Arch Haven',
                 'f': 'Frosted Fjord',
                 'gg': 'Creepy Crypt',
                 'hc': 'Creepy Crypt',
                 'om': 'Soggy Swamp',
                 'pc': 'Cacti Canyon',
                 'st': 'The Stronghold',
                 'sg': 'Obsidian Pinnacle',
                 'tsf': 'Desert Temple',
                 'ts': 'End Wilds',
                 'tts': 'Pumpkin Pastures',
                 'tt': 'Creeper Woods',
                 'tu': 'Nether Fortress',
                 'tg': 'Dingy Jungle',
                 'uo': 'Redstone Mines',
                 'ut': 'Nether Wastes',
                 'vm': 'Coral Rise',
                 'vs': 'Highblock Halls',
                 'wote': 'End wilds',
                 'w': 'Windswept Peaks'}

# _names_runes : A list of Ancient nicknames and the runes required to find them
_names_runes = {'?'   : 'Blue L, Red T, Sky Blue Y, Red Upside Down U',
                'aw'  : 'Pink Circle with Line on top, Blue + With Top Hook, Red Upside Down U',
                'ae'  : 'Blue L, Blue + With Top Hook, Red T',
                'at'  : 'Orange Man, Grey Chain Link, Pink Circle with Line on top, Red Upside Down U',
                'b'   : 'Grey Chain Link, Brown Fuzz (x2)',
                'cp'  : 'Blue L, Grey Chain Link, Red T',
                'fe'  : 'Grey Chain Link, Pink Circle with Line on top (x2)',
                'f'   : 'Orange Man, Pink Circle with Line on top, Brown Fuzz',
                'gg'  : 'Red T, Red T, Red Upside Down U',
                'hc'  : 'Brown Fuzz (x2), Red Upside Down U',
                'om'  : 'Orange Man, Blue L, Brown Fuzz',
                'pc'  : 'Blue L, Brown Fuzz, Red T',
                'st'  : 'Red Upside Down U (x2), Red T, Blue L',
                'sg'  : 'Pink Circle with Line on top, Brown Fuzz, Sky Blue Y, Blue + With Top Hook',
                'tsf' : 'Grey Chain Link (x2)',
                'ts'  : 'Blue L (x2), Brown Fuzz, Pink Circle with Line on top',
                'tts' : 'Blue L (x2), Grey Chain Link, Blue + With Top Hook',
                'tt'  : 'Orange Man (x2), Grey Chain Link, Sky Blue Y',
                'tu'  : 'Orange Man (x2), Blue + With Top Hook',
                'tg'  : 'Orange Man, Blue L (x2)',
                'uo'  : 'Red T, Blue + With Top Hook (x2)',
                'ut'  : 'Brown Fuzz, Red T, Red Upside Down U',
                'vm'  : 'Pink Circle with Line on top (x2), Blue + With Top Hook',
                'vs'  : 'Brown Fuzz, Red T (x2), Blue + With Top Hook',
                'wote': 'Blue + With Top Hook, Red Upside Down U, Blue L',
                'w'   : 'Orange Man, Red Upside Down U (x2)'}

# _names_mob : A list of Ancient nicknames and what they are
_names_mob = {'?'   : 'Mooshroom',
              'aw'  : 'Spider',
              'ae'  : 'Guardian',
              'at'  : 'Wraith',
              'b'   : 'Armored Skeleton',
              'cp'  : 'Skeleton Vanguard',
              'fe'  : 'Enchanter',
              'fw'  : 'Geomancer',
              'gg'  : 'Zombie',
              'hc'  : 'Necromancer',
              'om'  : 'Small Slime',
              'pc'  : 'Witch',
              'st'  : 'Silverfish',
              'sg'  : 'Pillager',
              'tsf' : 'Vex',
              'ts'  : 'Snareling',
              'tts' : 'Baby Zombie',
              'tt'  : 'Chicken Jockey Tower',
              'tu'  : 'Blaze Spawner',
              'tg'  : 'Leapleaf',
              'uo'  : 'Redstone Golem',
              'ut'  : 'Hoglin',
              'vm'  : 'Trident Drowned',
              'vs'  : 'Royal Guard',
              'wote': 'Watchling',
              'w'   : 'Goat'
              }

# _names_backup : A list of Ancient nicknames and their backup
_names_backup = {'?'   : 'Mooshroom',
                 'aw'  : 'Creeper',
                 'ae'  : 'Drowned Necromancer',
                 'at'  : 'Spider',
                 'b'   : 'Skeleton',
                 'cp'  : 'Baby Zombie',
                 'fe'  : 'Husk',
                 'fw'  : 'Iceologer',
                 'gg'  : 'Necromancer',
                 'hc'  : 'Skeleton Horsemen',
                 'om'  : 'Large Slime',
                 'pc'  : 'Necromancer',
                 'st'  : 'Skeleton',
                 'sg'  : 'Enderman',
                 'tsf' : 'Evoker',
                 'ts'  : 'Endermite',
                 'tts' : 'Redstone Golem',
                 'tt'  : 'Chicken Jockey',
                 'tu'  : 'Wither Skeleton Archer',
                 'tg'  : 'Whisperers',
                 'uo'  : 'Royal Guards',
                 'ut'  : 'Piglin Hunter',
                 'vm'  : 'Baby Drowned',
                 'vs'  : 'Pillager',
                 'wote': 'Blastling',
                 'w'   : 'Mountaineers'
                 }

# _names_drops: A list of Ancient nicknames and their drops
_names_drops = {'?'   : 'Dual Crossbows (Baby Crossbows, Spellbound Crossbows) : Gauntlets (Fighter\'s Bindings, Maulers, Soul Fists) : Ghostly Armor (Ghost Kindler) : Katana (Dark Katana, Master\'s Katana)',
                'aw'  : 'Battle Robe (Splendid Robe) : Double Axe (Cursed Axe, Whirlwind) : Trickbow (The Green Menace, The Pink Scoundrel) : Wolf Armor (Black Wolf Armor, Fox Armor)',
                'ae'  : 'Coral Blade (Sponge Striker) : Squid Armor (Glow Squid Armor) : Harpoon Crossbow (Nautical Crossbow)',
                'at'  : 'Exploding Crossbow (Firebolt Thrower, Imploding Crossbow) : Mystery Armor : Champion\'s Armor (Hero\'s Armor)',
                'b'   : 'Bow (Bonebow, Twin Bow) : Hunter\'s Armor (Archer\'s Armor) : Soul Bow (Bow of Lost Souls, Nocturnal Bow)',
                'cp'  : 'Cutlass (Dancer\'s Sword, Nameless Blade) : Phantom Armor (Frost Bite) : Soul Crossbow (Feral Soul Crossbow, Voidcaller)',
                'fe'  : 'Scale Mail (Highland Armor) : Claymore (Broadsword, Great Axeblade, Frost Slayer, Heartstealer) : Soul Scythe (Frost Scythe, Jailor\'s Scythe)',
                'fw'  : 'Snow Armor (Frost Armor) : Snow Bow (Winter\'s Touch)',
                'gg'  : 'Dark Armor (Titan\'s Shroud) : Grim Armor (Wither Armor) : Sword (Diamond Sword, Hawkbrand)',
                'hc'  : 'Longbow (Red Snake, Guardian Bow) : Rapid Crossbow (Auto Crossbow, Butterfly Crossbow) : Sickles (The Last Laugh, Nightmare\'s Bite) : Spelunker Armor (Cave Crawler)',
                'om'  : 'Battlestaff (Battlestaff of Terror, Growing Staff) : Shortbow (Love Spell Bow, Mechanical Shortbow, Purple Storm) : Mercenary Armor (Renegade Armor)',
                'pc'  : 'Glaive (Grave Bane, Venom Glaive) : Heavy Crossbow (Doom Crossbow, Slayer Crossbow) : Scatter Crossbow (Harp Crossbow, Lightning Harp Crossbow) : Spear (Fortune Spear, Whispering Spear)',
                'st'  : 'Obsidian Claymore (The Starless Night) : Teleportation Robes (Unstable Robes) : Void Bow (Call of the Void)',
                'sg'  : 'Burst Crossbow (Corrupted Crossbow, Soul Hunter Crossbow) : Rapier (Bee Stinger, Freezing Foil) : Guard\'s Armor',
                'tsf' : 'Axe (Firebrand, Highland Axe) : Evocation Robe (Ember Robe, Verdant Robe) : Soul Knife (Eternal Knife, Truthseeker)',
                'ts'  : 'Backstabber (Swift Striker) : Shulker Armor (Sturdy Shulker Armor) : Shadow Crossbow (Veiled Crossbow)',
                'tts' : 'Daggers (Fangs of Frost, Moon Daggers, Sharp Daggers) : Soul Robe (Souldancer Robe) : Thief Armor (Spider Armor)',
                'tt'  : 'Hunting Bow (Ancient Bow, Hunter\'s Promise, Master\'s Bow) : Beenest Armor (Beehive Armor) : Pickaxe (Diamond Pickaxe)',
                'tu'  : 'Boneclub (Bone Cudgel) : Piglin Armor (Golden Piglin Armor) : Twisting Vine Bow (Weeping Vine Bow)',
                'tg'  : 'Ocelot Armor (Shadow Walker) : Whip (Vine Whip) : Root Rot Armor (Black Spot Armor)',
                'uo'  : 'Great Hammer (Hammer of Gravity, Stormlander) : Claymore (Broadsword, Great Axeblade, Heartstealer) : Power Bow (Elite Power Bow, Sabrewing) : Plate Armor (Full Metal Armor)',
                'ut'  : 'Broken Sawblade (Mechanized Sawblade) : Cog Crossbow (Pride of the Piglins) : Sprout Armor (Living Vines Armor)',
                'vm'  : 'Anchor (Encrusted Anchor) : Bubble Bow (Bubble Burster) : Turtle Armor (Nimble Turtle Armor)',
                'vs'  : 'Crossbow (Azure Seeker, The Slicer) : Mace (Flail, Sun\'s Grace) : Reinforced Mail (Stalwart Armor)',
                'wote': 'Entertainer\'s Garb (The Troubadour) : Shadow Crossbow (Veiled Crossbow) : Void Touched Blades (The Beginning and The End)',
                'w'   : 'Climbing Gear (Goat Gear, Rugged Climbing Gear) : Emerald Gear (Gilded Glory, Opulent Armor) : Tempest Knife (Chill Gale Knife, Resolute Tempest Knife) : Wind Bow (Burst Gale Bow, Echo of the Valley)'
                }

# _names_enchants: A list of Ancient nicknames and their minimum enchantments
_names_enchants = {'?'   : 'Deflect, Leeching, Poison Cloud, Thorns',
                   'aw'  : 'Frenzied, Mob Resurrection Aura, Multishot, Regeneration',
                   'ae'  : 'Electrified, Quick, Frenzied, Heals Allies',
                   'at'  : 'Burning, Chilling, Electrified, Fire Trail',
                   'b'   : 'Accelerate, Multishot, Ricochet, Rapid Fire',
                   'cp'  : 'Chilling, Gravity Pulse, Poison Cloud',
                   'fe'  : 'Critical Hit, Echo, Freezing',
                   'fw'  : 'Chilling, Deflect',
                   'gg'  : 'Echo, Protection, Quick, Radiance',
                   'hc'  : 'Accelerate, Fire Trail, Gravity Pulse, Rapid Fire, Regeneration',
                   'om'  : 'Gravity, Huge, Poison Cloud',
                   'pc'  : 'Deflect, Heals Allies, Quick',
                   'st'  : 'Burning, Cowardice, Regeneration',
                   'sg'  : 'Huge, Multishot, Radiance Shot, Ricochet',
                   'tsf' : 'Burning, Fire Aspect, Fire Trail, Huge',
                   'ts'  : 'Bonus Shot, Gravity, Mob Resurrection Aura',
                   'tts' : 'Fast Attack, Fire Aspect, Frenzied, Thorns',
                   'tt'  : 'Commited, Critical Hit, Freezing',
                   'tu'  : 'Chilling, Heals Allies, Burning',
                   'tg'  : 'Deflect, Electrified, Shockwave',
                   'uo'  : 'Commited, Electrified, Frenzied, Swirling',
                   'ut'  : 'Fire Trail, Poison Cloud, Quick, Rampaging',
                   'vm'  : 'Critical Hit, Deflect, Fast Attack, Gravity Pulse',
                   'vs'  : 'Freezing, Sharpness, Thundering',
                   'wote': 'Deflect, Echo, Heals Allies',
                   'w'   : 'Double Damage, Fire Trail, Quick, Regeneration, Burning'
                   }

# _names_backup_ench: A list of ancient nicknames and their backup's enchantments
_names_backup_ench = {'?'   : 'Weakening',
                      'aw'  : 'Deflect, Quick',
                      'ae'  : 'Double Damage',
                      'at'  : 'Weakening',
                      'b'   : 'Accelerate',
                      'cp'  : 'Burning',
                      'fe'  : 'Swirling',
                      'fw'  : 'Thorns',
                      'gg'  : 'Heals Allies',
                      'hc'  : 'Cowardice',
                      'om'  : 'Shockwave',
                      'pc'  : 'Mutlishot',
                      'st'  : 'Growing',
                      'sg'  : 'Radiance',
                      'tsf' : 'Chilling',
                      'ts'  : 'Thorns',
                      'tts' : 'Weakening',
                      'tt'  : 'Electrified',
                      'tu'  : 'Chain Reaction, Tempo Theft',
                      'tg'  : 'Electrified',
                      'uo'  : 'Regeneration',
                      'ut'  : 'Fuse Shot',
                      'vm'  : 'Regeneration',
                      'vs'  : 'Poison Cloud, Tempo Theft',
                      'wote': 'Radiance Shot',
                      'w'   : 'Regeneration'
                      }


def lookup(name):
    try:nick = _names[name.lower().replace(' ', '_')]
    except KeyError:return 'No such ancient'
    print('Spawns in', _names_places[nick])
    print('Is an ancient version of', _names_mob[nick])
    print('Requires Runes :', _names_runes[nick])
    print('Backup:', _names_backup[nick])
    print('Enchanted with', _names_enchants[nick])
    print('Backup enchanted with :', _names_backup_ench[nick])
    print('Can drop------------------\n', _names_drops[nick].replace(' : ', '\n'))
    print('------------------------------------------------------------------------------------------------------------------------')
    
